networks:
  app_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16

services:
  postgres:
    image: postgres:latest
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: my-app
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      app_network:
        ipv4_address: 172.28.0.11

  backend:
    image: phuong06061994/java-demo:1be12d
    container_name: backend-app
    ports:
      - "50002:8080"
    networks:
      app_network:
        ipv4_address: 172.28.0.12
    depends_on:
      - postgres

  frontend:
    image: phuong06061994/angular-demo:ad8bb2
    container_name: frontend-app
    ports:
      - "3000:80"
    networks:
      app_network:
        ipv4_address: 172.28.0.13
    depends_on:
      - backend

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "80:80"
    networks:
      app_network:
        ipv4_address: 172.28.0.14
    depends_on:
      - frontend
      - backend
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d
    
volumes:
  postgres_data:
